### ISSUE TITLE
docker run instructions not 100% reliable

### ISSUE THREAD

**Issue by divv** [RileyWilliams/pycryptodome-aws-lambda#1]
Trying the instructions as is left me with an out directory with nothing in it.

The below worked better:
 docker run -ti -v $(pwd):/out -w /out ami-pycrypto

Obviously non-ideal to put it straight in the current working dir. I suspect that permissions were at play here. May be worth mentioning in instructions?

**Comment by RileyWilliams** [comment]
Hi @divv, nice find, I'll update the instructions to include your fix, cheers.
